version: '3.8'

services:
  wetty:
    build:
      context: . # Directorio donde est√° tu Dockerfile.dev/Directory where your Dockerfile.dev is located
      dockerfile: Dockerfile.dev
    container_name: wetty-dev
    image: wetty:dev # Nombre y tag personalizados/Custom name and tag
    ports:
      - "3000:3000"
    volumes:
      #- ./share:/home/testuser # is used only for testing
      - ./themes:/usr/src/app/build/shared/themes
    # command: --base / --allow-iframe
    command: --base / --ssh-host tmate-server --ssh-port 2200 --allow-iframe
    networks:
      - local
    restart: unless-stopped
networks:
  local:
    external: true  # Use the existing 'local' network from tmate-server

